# Generated by Django 4.0.3 on 2022-04-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('street_num', models.IntegerField()),
                ('street_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('home_address_id', models.CharField(max_length=200)),
                ('billing_address_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('parent_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_num', models.CharField(max_length=200)),
                ('card_code', models.IntegerField()),
                ('expire_month', models.IntegerField()),
                ('expire_year', models.IntegerField()),
                ('card_type', models.CharField(max_length=200)),
                ('owner_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocalVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('business_address_id', models.CharField(max_length=200)),
                ('customer_service_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('seller_email', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('buyer_email', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('payment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField(unique=True)),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('price', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.CharField(max_length=200)),
                ('seller_email', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('rating_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.CharField(max_length=200)),
                ('seller_email', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('review_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('routing_number', models.CharField(max_length=200)),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZipcodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state_id', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('density', models.FloatField()),
                ('county_name', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
            ],
        ),
    ]
